server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME} 
 
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
      - id: serviceOne
        uri: lb://SERVICE-USER
        predicates:
        - Path=/service-user/***
      - id: serviceTwo
        uri: lb://EMAIL-SERVICE
        predicates:
        - Path=/email-service/***
      - id: serviceThree
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment-service/***

