spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ezolarteam@gmail.com
    password: vkbyfvhiyuaquodc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /service-email
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 
    hostname: ${COMPUTERNAME}


      
